# Generated by Django 5.0.2 on 2024-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50, verbose_name='заголовок статьи')),
                ('article_body', models.TextField(verbose_name='содержимое статьи')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='изображение статьи')),
                ('publicated_date', models.DateTimeField(verbose_name='дата публикации')),
                ('count_views', models.PositiveIntegerField(verbose_name='количество просмотров')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
