# Generated by Django 5.0.2 on 2024-05-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmail', '0002_client_client_owner_logs_logs_owner_mail_mail_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('deactivate_articles', 'Can deactivate articles')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
